CREATE DATABASE CASADESHOW;

USE CASADESHOW;

CREATE TABLE EVENTOS(
EVENTOID INT PRIMARY KEY AUTO_INCREMENT,
NOMEEVENTO VARCHAR(255) NOT NULL,
DATAEVENTO DATE NOT NULL,
LOCALIZACAO VARCHAR(255) NOT NULL
);

CREATE TABLE PARTICIPANTES(
PARTICIPANTEID INT PRIMARY KEY AUTO_INCREMENT,
NOMEPARTICIPANTE VARCHAR(255) NOT NULL,
EMAIL VARCHAR(100) NOT NULL UNIQUE,
TELEFONE VARCHAR(12) NOT NULL
);

CREATE TABLE INSCRICOESEVENTOS(
INSCRICAOID INT PRIMARY KEY AUTO_INCREMENT,
EVENTOID INT NOT NULL,
PARTICIPANTEID INT NOT NULL,
FOREIGN KEY (EVENTOID) REFERENCES EVENTOS(EVENTOID),
FOREIGN KEY (PARTICIPANTEID) REFERENCES PARTICIPANTES(PARTICIPANTEID)
);
DROP TABLE INSCRICOESEVENTOS;
INSERT INTO EVENTOS(NOMEEVENTO, DATAEVENTO, LOCALIZACAO)
VALUES 
	('AGUAVIVA','2023-11-20','ONDINA' ),
    ('LOBOS DA LUA','2023-10-12','BARRA' ),
    ('MEIA NOITE','2023-10-28','VILAS' ),
    ('LUA CHEIA','2023-12-15','CAJAZEIRA' ),
    ('SOL DO DIA','2023-12-05','DENDEZEIROS' );
    
INSERT INTO PARTICIPANTES(NOMEPARTICIPANTE, EMAIL, TELEFONE)
VALUES
	("Dario Lucas", "DLSANTOS@GMAIL.COM", "7196543-1594"),
    ("Marcos Paulo", "MPAULO@GMAIL.COM", "7191745-1594"),
    ("Froid Mercuri", "FMERCURI@GMAIL.COM", "7196584-1594"),
    ("Lona Souza", "LSOUZA@GMAIL.COM", "7192548-1594"),
    ("Fernando Muerte", "FMUERTE@GMAIL.COM", "7192548-1594"),
    ("Lucas Inutilismo", "LINUTILISMO@GMAIL.COM", "7191957-1594");
    
INSERT INTO  INSCRICOESEVENTOS(EVENTOID, PARTICIPANTEID)
VALUES
	(1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5)
    ;
    
SELECT E.NOMEEVENTO, P.NOMEPARTICIPANTE
FROM EVENTOS AS E
JOIN INSCRICOESEVENTOS AS I ON I.EVENTOID = E.EVENTOID
JOIN PARTICIPANTES AS P ON I.PARTICIPANTEID = P.PARTICIPANTEID;

SELECT A.NOMEALUNO, C.NOMECURSO
FROM ALUNOS AS A
JOIN INSCRICOES AS I ON A.MATRICULA = I.MATRICULAALUNO 
JOIN CURSOS AS C ON I.CURSOID = C.CURSOID
    