CREATE DATABASE EMPRESA;

USE EMPRESA;

CREATE TABLE EMPRESA.CLIENTE( 
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Telefone VARCHAR(22) NOT NULL,
    Id_Endereco INT,
    FOREIGN KEY (Id_Endereco) REFERENCES EMPRESA.ENDERECOS(Id)
);

CREATE TABLE EMPRESA.ENDERECOS(
	Id INT AUTO_INCREMENT  PRIMARY KEY,
    Logradouro VARCHAR(255) NOT NULL,
    Cep VARCHAR(11) NOT NULL,
    Numero VARCHAR(5),
    Complemento VARCHAR(255),
    Cidade VARCHAR(255) NOT NULL
);

